app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

tasks:
    resource: "@AppBundle/Controller/TaskController.php"
    type: rest
    prefix: /api

fallback:
    path: /{url}
    defaults: { _controller: AppBundle:Default:index, url: null }
    requirements:
      url: .*